
name: "🔐 Cannot Connect / Authentication Help"
description: Get help connecting your MCP client or authenticating
title: "[Auth/Connect]: "
labels: ["question","auth","connectivity","help-wanted"]
body:
  - type: markdown
    attributes:
      value: |
        **Having trouble connecting an MCP client or authenticating?** Fill out this form so we can diagnose the issue more accurately.
        Please redact secrets. Exact error messages are extremely helpful.
  - type: dropdown
    id: client_type
    attributes:
      label: MCP client
      description: Which client are you using?
      options:
        - Agentforce Vibes
        - Cursor
        - Claude Code
        - Claude Desktop
        - Claude (Web)
        - ChatGPT / OpenAI
        - Windsurf
        - VS Code (extension)
        - Google ADK (custom)
        - In-house / custom
        - Other
    validations:
      required: true
  - type: input
    id: client_other
    attributes:
      label: If "Other", which client?
      placeholder: Name and vendor
  - type: input
    id: client_version
    attributes:
      label: Client version
      placeholder: e.g., Claude Desktop 1.xx / Cursor x.y.z
  - type: dropdown
    id: auth_flow
    attributes:
      label: Authentication flow attempted
      options:
        - Client Credentials (recommended for server-to-server)
        - Authorization Code (browser)
        - Other / Not sure
    validations:
      required: true
  - type: input
    id: eca_id
    attributes:
      label: External Client App identifier (if known)
      placeholder: "ECA name or ID in Salesforce Setup"
  - type: input
    id: scopes
    attributes:
      label: OAuth scopes granted
      placeholder: "Include MCP-specific scope, if any"
  - type: input
    id: org_context
    attributes:
      label: Org context
      description: Dev, Sandbox, or Scratch
      placeholder: "Dev org • NA###"
  - type: checkboxes
    id: network
    attributes:
      label: Network environment
      options:
        - label: Corporate proxy or egress filtering may apply
        - label: VPN in use
        - label: mTLS or custom CA certs involved
        - label: None of the above
  - type: textarea
    id: endpoint
    attributes:
      label: Endpoint configuration
      description: MCP server URL, port, and any client settings (redact secrets).
      render: text
  - type: textarea
    id: token_steps
    attributes:
      label: Token acquisition steps
      description: Commands or UI steps taken to obtain the access token. Include the token endpoint and grant_type (redact secrets).
      render: shell
  - type: textarea
    id: error_output
    attributes:
      label: Error messages
      description: Paste exact error(s), including HTTP status codes and response bodies where possible (redact sensitive values).
      render: shell
    validations:
      required: true
  - type: checkboxes
    id: common_causes
    attributes:
      label: I have already checked the following common causes
      options:
        - label: Incorrect audience / resource / scope parameters
        - label: Using a Connected App instead of External Client App
        - label: Token issued for wrong environment (e.g., login vs test domain)
        - label: Proxy stripping auth headers
        - label: mTLS handshake failures (cert chain/hostnames)
        - label: Mis-typed server URL or path
  - type: textarea
    id: steps_tried
    attributes:
      label: What I’ve tried
      description: List workarounds or experiments already attempted.
  - type: textarea
    id: attachments
    attributes:
      label: Attachments
      description: Screenshots or logs. Please redact secrets.
